version: '3.9'

services:

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sms_django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      # - mysql
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: sms_redis
    ports:
      - "6379:6379"

  # mysql:
  #   image: mysql:8.0
  #   container_name: sms_mysql
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: sms_db
  #     MYSQL_USER: torjo
  #     MYSQL_PASSWORD: sms_1234
  #     MYSQL_ROOT_PASSWORD: torjo1234
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sms_celery_worker
    command: celery -A SMS worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      # - mysql
    env_file:
      - .env

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sms_celery_beat
    command: celery -A SMS beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      # - mysql
    env_file:
      - .env

# volumes:
#   mysql_data:
