services:

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sms_django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    env_file:
      - .env


  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sms_celery_worker
    command: celery -A SMS worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sms_celery_beat
    command: celery -A SMS beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
volumes:
  mysql_data: